version: '3.7'
services:
    vertica:
        image: dataplatform/docker-vertica
        ports:
            - 5433:5433
        volumes:
            - ./dataset:/tmp/dataset
            - /data/vertica/vertica_data:/home/dbadmin/docker
